"""Store interfaces (TSD §5.3).

Keeping vector and graph behind Protocols lets us swap the default embedded SQLite store
for Postgres+pgvector (teams) or a decentralized backend (ADR-010) without touching callers.
"""

from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from ..models import Edge, Hit, Memory


@runtime_checkable
class VectorStore(Protocol):
    """ANN vector index. Default impl: sqlite-vec (the strand is one SQLite file)."""

    def upsert(self, id: str, embedding: list[float], payload: dict[str, Any]) -> None: ...

    def query(
        self, embedding: list[float], k: int, filters: dict[str, Any] | None = None
    ) -> list[Hit]: ...

    def delete(self, id: str) -> None: ...


@runtime_checkable
class GraphStore(Protocol):
    """Typed knowledge graph. Default impl: SQLite tables + NetworkX projections."""

    def add_node(self, node: Memory) -> None: ...

    def get_node(self, id: str) -> Memory | None: ...

    def add_edge(self, edge: Edge) -> None: ...

    def neighbors(self, id: str, depth: int = 1) -> list[Memory]: ...

    def all(self) -> list[Memory]: ...


@runtime_checkable
class BlobStore(Protocol):
    """Opaque content-addressed blobs (e.g., large provenance payloads)."""

    def put(self, data: bytes) -> str:  # returns content hash
        ...

    def get(self, digest: str) -> bytes | None: ...


@runtime_checkable
class Store(Protocol):
    """The full memory-store surface the engine depends on (ADR-018).

    `SqliteStore` is the default (one portable file); `PgVectorStore` is an experimental
    Postgres+pgvector backend for large shared/team strands. Any conforming object can be
    swapped in behind the engine.
    """

    def tx(self): ...  # context manager: atomic write
    def ensure_embedding_space(self, model: str, dim: int) -> None: ...
    def upsert_memory(self, mem: Memory, embedding: list[float] | None = None) -> None: ...
    def get_memory(self, memory_id: str) -> Memory | None: ...
    def all_memories(self, scope=None, statuses=..., limit: int = 1000) -> list[Memory]: ...
    def count(self, statuses=...) -> int: ...
    def vector_search(
        self, query_vec: list[float], k: int, scope=None
    ) -> list[tuple[str, float]]: ...
    def keyword_search(self, query: str, k: int, scope=None) -> list[tuple[str, float]]: ...
    def neighbors(self, memory_id: str, depth: int = 1) -> list[Memory]: ...
    def all_edges(self) -> list[Edge]: ...
    def edge_count(self) -> int: ...
    def add_edge(self, edge: Edge) -> None: ...
    def add_history(self, op: str, memory_id: str, detail=None) -> None: ...
    def history(self, limit: int = 100) -> list[dict]: ...
    def set_meta(self, key: str, value: str) -> None: ...
    def get_meta(self, key: str) -> str | None: ...
    def fingerprints(self) -> list[str]: ...
    def reembed(self, embedder) -> int: ...
    def get_version(self) -> int: ...
    def bump_version(self) -> int: ...
    def close(self) -> None: ...
